* VIF(方差膨胀系数)

In [1]:
import numpy as np
import pandas as pd
import joblib
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [2]:
#加载数据
pd_data = joblib.load("../data/train_woe.pkl")
pd_data

SK_ID_CURR  TARGET  AMT_GOODS_PRICE  REGION_POPULATION_RELATIVE  \
125406      245429       0         0.610118                    0.016406   
8155        109510       0        -0.366495                   -0.410334   
154053      278546       0         0.038650                    0.016406   
300963      448668       0        -0.366495                   -0.158446   
269546      412373       0        -0.366495                   -0.410334   
...            ...     ...              ...                         ...   
298994      446376       0        -0.050233                    0.016406   
269429      412242       0        -0.050233                    0.016406   
16          100020       0         0.268859                    0.268275   
97169       212804       0         0.038650                    0.016406   
90581       205165       0        -0.050233                   -0.043274   

        DAYS_BIRTH  DAYS_EMPLOYED  DAYS_REGISTRATION  DAYS_ID_PUBLISH  \
125406    0.301190       0.092078          -0.099822         0.275679   
8155     -0.440745      -0.608958           0.164707         0.193847   
154053    0.301190       0.371651           0.075169         0.060654   
300963    0.301190      -0.171601           0.075169        -0.057870   
269546   -0.051704      -0.171601          -0.099822        -0.297834   
...            ...            ...                ...              ...   
298994   -0.440745      -0.451249          -0.377708        -0.297834   
269429   -0.440745       0.253381           0.075169         0.060654   
16        0.301190       0.253381          -0.099822        -0.057870   
97169    -0.440745      -0.451249           0.075169        -0.057870   
90581     0.301190       0.092078           0.075169         0.060654   

        REGION_RATING_CLIENT_W_CITY  REG_CITY_NOT_LIVE_CITY  ...  \
125406                    -0.020586               -0.048048  ...   
8155                      -0.536494               -0.048048  ...   
154053                    -0.020586               -0.048048  ...   
300963                    -0.020586               -0.048048  ...   
269546                    -0.536494               -0.048048  ...   
...                             ...                     ...  ...   
298994                    -0.020586               -0.048048  ...   
269429                    -0.020586               -0.048048  ...   
16                        -0.020586                0.459100  ...   
97169                     -0.536494               -0.048048  ...   
90581                     -0.020586               -0.048048  ...   

        p_NAME_SELLER_INDUSTRY_Connectivity  p_NAME_YIELD_GROUP_XNA  \
125406                             0.053257                0.383810   
8155                              -0.065479               -0.090837   
154053                            -0.065479               -0.090837   
300963                            -0.065479               -0.090837   
269546                             0.053257               -0.090837   
...                                     ...                     ...   
298994                             0.053257               -0.040815   
269429                            -0.065479               -0.090837   
16                                -0.065479               -0.090837   
97169                             -0.065479               -0.090837   
90581                             -0.065479               -0.090837   

        p_NAME_YIELD_GROUP_high  p_NAME_YIELD_GROUP_low_action  \
125406                 0.065650                       0.073290   
8155                  -0.132787                       0.073290   
154053                -0.132787                      -0.316556   
300963                -0.132787                      -0.316556   
269546                 0.110022                      -0.152116   
...                         ...                            ...   
298994                 0.110022                       0.073290   
269429                -0.132787 

In [4]:
pd_x = pd_data.drop(['SK_ID_CURR','TARGET'],axis=1)
pd_x

AMT_GOODS_PRICE  REGION_POPULATION_RELATIVE  DAYS_BIRTH  \
125406         0.610118                    0.016406    0.301190   
8155          -0.366495                   -0.410334   -0.440745   
154053         0.038650                    0.016406    0.301190   
300963        -0.366495                   -0.158446    0.301190   
269546        -0.366495                   -0.410334   -0.051704   
...                 ...                         ...         ...   
298994        -0.050233                    0.016406   -0.440745   
269429        -0.050233                    0.016406   -0.440745   
16             0.268859                    0.268275    0.301190   
97169          0.038650                    0.016406   -0.440745   
90581         -0.050233                   -0.043274    0.301190   

        DAYS_EMPLOYED  DAYS_REGISTRATION  DAYS_ID_PUBLISH  \
125406       0.092078          -0.099822         0.275679   
8155        -0.608958           0.164707         0.193847   
154053       0.371651           0.075169         0.060654   
300963      -0.171601           0.075169        -0.057870   
269546      -0.171601          -0.099822        -0.297834   
...               ...                ...              ...   
298994      -0.451249          -0.377708        -0.297834   
269429       0.253381           0.075169         0.060654   
16           0.253381          -0.099822        -0.057870   
97169       -0.451249           0.075169        -0.057870   
90581        0.092078           0.075169         0.060654   

        REGION_RATING_CLIENT_W_CITY  REG_CITY_NOT_LIVE_CITY  \
125406                    -0.020586               -0.048048   
8155                      -0.536494               -0.048048   
154053                    -0.020586               -0.048048   
300963                    -0.020586               -0.048048   
269546                    -0.536494               -0.048048   
...                             ...                     ...   
298994                    -0.020586               -0.048048   
269429                    -0.020586               -0.048048   
16                        -0.020586                0.459100   
97169                     -0.536494               -0.048048   
90581                     -0.020586               -0.048048   

        REG_CITY_NOT_WORK_CITY  EXT_SOURCE_2  ...  \
125406               -0.109312     -0.194908  ...   
8155                 -0.109312     -1.045357  ...   
154053               -0.109312      0.357743  ...   
300963               -0.109312      0.951342  ...   
269546                0.306831     -0.194908  ...   
...                        ...           ...  ...   
298994               -0.109312     -1.045357  ...   
269429               -0.109312      0.357743  ...   
16                    0.306831      0.357743  ...   
97169                -0.109312      0.013503  ...   
90581                 0.306831     -0.533934  ...   

        p_NAME_SELLER_INDUSTRY_Connectivity  p_NAME_YIELD_GROUP_XNA  \
125406                             0.053257                0.383810   
8155                              -0.065479               -0.090837   
154053                            -0.065479               -0.090837   
300963                            -0.065479               -0.090837   
269546                             0.053257               -0.090837   
...                                     ...                     ...   
298994                             0.053257               -0.040815   
269429                            -0.065479               -0.090837   
16                                -0.065479               -0.090837   
97169                             -0.065479               -0.090837   
90581                             -0.065479               -0.090837   

        p_NAME_YIELD_GROUP_high  p_NAME_YIELD_GROUP_low_action  \
125406                 0.065650                       0.073290   
8155                  -0.132787                       0.073290   
154053                -0.

In [8]:
#自定义方差膨胀系数计算函数
def check_vif(df):
    col_list = df.columns
    #variance_inflation_factor(参数一，参数二)
    #参数一：ndarray
    #参数二：int
    x = df.values  #样本数据
    #把列的id扔进来，计算每一个列的VIF
    vif_list = [variance_inflation_factor(x,i) for i in range(x.shape[1])]
    #创建df，让显示更人性化
    VIF = pd.DataFrame({'feature':col_list,
                  'VIF':vif_list})
    return VIF

In [10]:
df_vif = check_vif(pd_x)
df_vif

C:\Programming\Anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:193: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)
C:\Programming\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1717: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.uncentered_tss


feature       VIF
0                                    AMT_GOODS_PRICE  1.181193
1                         REGION_POPULATION_RELATIVE  1.848021
2                                         DAYS_BIRTH  3.322928
3                                      DAYS_EMPLOYED  1.689302
4                                  DAYS_REGISTRATION  1.182928
..                                               ...       ...
72                 p_PRODUCT_COMBINATION_Card Street  2.282718
73           p_PRODUCT_COMBINATION_Cash Street: high  2.392276
74           p_PRODUCT_COMBINATION_Cash X-Sell: high  1.933213
75            p_PRODUCT_COMBINATION_Cash X-Sell: low  2.112973
76  p_PRODUCT_COMBINATION_POS industry with interest  2.045593

[77 rows x 2 columns]

In [11]:
df_vif[df_vif['VIF'] > 3]


feature       VIF
2                    DAYS_BIRTH  3.322928
11  YEARS_BEGINEXPLUATATION_AVG  4.558895
12               FLOORSMAX_MEDI  5.452477
13               TOTALAREA_MODE  5.242828
16   AMT_REQ_CREDIT_BUREAU_YEAR  4.186162
18   NAME_INCOME_TYPE_Pensioner  3.437966
23       EMERGENCYSTATE_MODE_No  3.851456
27         b_CREDIT_DAY_OVERDUE       inf
33     b_AMT_CREDIT_SUM_OVERDUE       inf
35       b_CREDIT_TYPE_Car loan  3.136588
38       b_CREDIT_TYPE_Mortgage       inf
65         p_NAME_PORTFOLIO_POS  3.288162
68       p_NAME_YIELD_GROUP_XNA  4.261597

* 递归特征消除RFE

In [12]:
from sklearn.feature_selection import RFE
from sklearn.svm import LinearSVC
from sklearn.datasets import load_iris

#导包快捷键：Alt + Enter
#加载数据
x,y = load_iris(return_X_y=True)
svc = LinearSVC(C=0.01)
selector = RFE(svc,n_features_to_select=2,step=1)


In [13]:
selector.fit(x,y)


RFE(estimator=LinearSVC(C=0.01), n_features_to_select=2)

In [16]:
selector.support_

array([3, 1, 1, 2])

In [15]:
selector.ranking_

array([3, 1, 1, 2])

* L1特征消除


In [18]:
iris = load_iris()
x = iris['data']
y = iris['target']

In [19]:
x.shape


(150, 4)

In [20]:
svc = LinearSVC(C=0.01,penalty='l1',dual=False)
model = svc.fit(x,y)

C:\Programming\Anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [22]:
from sklearn.feature_selection import SelectFromModel

selector_model = SelectFromModel(model,prefit=True)
#保留最重要的特征，去掉了最不重要的特征
#后续可以使用留下的特征数据去训练模型即可
x_new = selector_model.transform(x)

In [23]:
x_new.shape


(150, 3)

In [24]:
x_new

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4],
       [5.4, 3.9, 1.7],
       [4.6, 3.4, 1.4],
       [5. , 3.4, 1.5],
       [4.4, 2.9, 1.4],
       [4.9, 3.1, 1.5],
       [5.4, 3.7, 1.5],
       [4.8, 3.4, 1.6],
       [4.8, 3. , 1.4],
       [4.3, 3. , 1.1],
       [5.8, 4. , 1.2],
       [5.7, 4.4, 1.5],
       [5.4, 3.9, 1.3],
       [5.1, 3.5, 1.4],
       [5.7, 3.8, 1.7],
       [5.1, 3.8, 1.5],
       [5.4, 3.4, 1.7],
       [5.1, 3.7, 1.5],
       [4.6, 3.6, 1. ],
       [5.1, 3.3, 1.7],
       [4.8, 3.4, 1.9],
       [5. , 3. , 1.6],
       [5. , 3.4, 1.6],
       [5.2, 3.5, 1.5],
       [5.2, 3.4, 1.4],
       [4.7, 3.2, 1.6],
       [4.8, 3.1, 1.6],
       [5.4, 3.4, 1.5],
       [5.2, 4.1, 1.5],
       [5.5, 4.2, 1.4],
       [4.9, 3.1, 1.5],
       [5. , 3.2, 1.2],
       [5.5, 3.5, 1.3],
       [4.9, 3.6, 1.4],
       [4.4, 3. , 1.3],
       [5.1, 3.4, 1.5],
       [5. , 3.5, 1.3],
       [4.5, 2.3