In [2]:
import numpy as np
import pandas as pd
import joblib
from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy


In [4]:
pd_data = joblib.load('../data/train_woe.pkl')
pd_data

SK_ID_CURR  TARGET  AMT_GOODS_PRICE  REGION_POPULATION_RELATIVE  \
125406      245429       0         0.610118                    0.016406   
8155        109510       0        -0.366495                   -0.410334   
154053      278546       0         0.038650                    0.016406   
300963      448668       0        -0.366495                   -0.158446   
269546      412373       0        -0.366495                   -0.410334   
...            ...     ...              ...                         ...   
298994      446376       0        -0.050233                    0.016406   
269429      412242       0        -0.050233                    0.016406   
16          100020       0         0.268859                    0.268275   
97169       212804       0         0.038650                    0.016406   
90581       205165       0        -0.050233                   -0.043274   

        DAYS_BIRTH  DAYS_EMPLOYED  DAYS_REGISTRATION  DAYS_ID_PUBLISH  \
125406    0.301190       0.092078          -0.099822         0.275679   
8155     -0.440745      -0.608958           0.164707         0.193847   
154053    0.301190       0.371651           0.075169         0.060654   
300963    0.301190      -0.171601           0.075169        -0.057870   
269546   -0.051704      -0.171601          -0.099822        -0.297834   
...            ...            ...                ...              ...   
298994   -0.440745      -0.451249          -0.377708        -0.297834   
269429   -0.440745       0.253381           0.075169         0.060654   
16        0.301190       0.253381          -0.099822        -0.057870   
97169    -0.440745      -0.451249           0.075169        -0.057870   
90581     0.301190       0.092078           0.075169         0.060654   

        REGION_RATING_CLIENT_W_CITY  REG_CITY_NOT_LIVE_CITY  ...  \
125406                    -0.020586               -0.048048  ...   
8155                      -0.536494               -0.048048  ...   
154053                    -0.020586               -0.048048  ...   
300963                    -0.020586               -0.048048  ...   
269546                    -0.536494               -0.048048  ...   
...                             ...                     ...  ...   
298994                    -0.020586               -0.048048  ...   
269429                    -0.020586               -0.048048  ...   
16                        -0.020586                0.459100  ...   
97169                     -0.536494               -0.048048  ...   
90581                     -0.020586               -0.048048  ...   

        p_NAME_SELLER_INDUSTRY_Connectivity  p_NAME_YIELD_GROUP_XNA  \
125406                             0.053257                0.383810   
8155                              -0.065479               -0.090837   
154053                            -0.065479               -0.090837   
300963                            -0.065479               -0.090837   
269546                             0.053257               -0.090837   
...                                     ...                     ...   
298994                             0.053257               -0.040815   
269429                            -0.065479               -0.090837   
16                                -0.065479               -0.090837   
97169                             -0.065479               -0.090837   
90581                             -0.065479               -0.090837   

        p_NAME_YIELD_GROUP_high  p_NAME_YIELD_GROUP_low_action  \
125406                 0.065650                       0.073290   
8155                  -0.132787                       0.073290   
154053                -0.132787                      -0.316556   
300963                -0.132787                      -0.316556   
269546                 0.110022                      -0.152116   
...                         ...                            ...   
298994                 0.110022                       0.073290   
269429                -0.132787 

In [6]:
#加载x和y，要求是array数据
data = pd_data.drop(['SK_ID_CURR','TARGET'],axis=1)
x = data.values
#从原始数据中获取y值
y = pd_data['TARGET'].values

In [7]:
x


array([[ 0.61011757,  0.0164057 ,  0.30118966, ..., -0.03366097,
         0.083527  , -0.06584093],
       [-0.3664945 , -0.41033385, -0.44074513, ..., -0.03366097,
         0.083527  , -0.34852914],
       [ 0.03864971,  0.0164057 ,  0.30118966, ..., -0.03366097,
         0.083527  , -0.34852914],
       ...,
       [ 0.2688592 ,  0.2682751 ,  0.30118966, ..., -0.03366097,
         0.083527  ,  0.08450937],
       [ 0.03864971,  0.0164057 , -0.44074513, ..., -0.03366097,
         0.083527  ,  0.08450937],
       [-0.05023317, -0.04327434,  0.30118966, ..., -0.03366097,
         0.083527  , -0.34852914]])

In [8]:
y


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [9]:
#将多维数据降为一维
y = y.ravel()
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [10]:
#创建分类器，这里选择的是集成学习，因为集成学习中有特征重要性
rf = RandomForestClassifier(n_jobs=-1,
                       class_weight='balanced',
                       max_depth=5)
boruta = BorutaPy(rf,n_estimators='auto',random_state=1,max_iter=10)
boruta.fit(x, y)

BorutaPy(estimator=RandomForestClassifier(class_weight='balanced', max_depth=5,
                                          n_estimators=248, n_jobs=-1,
                                          random_state=RandomState(MT19937) at 0x279444E5240),
         max_iter=10, n_estimators='auto',
         random_state=RandomState(MT19937) at 0x279444E5240)

In [11]:
boruta.support_

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [12]:
#值越大，说明越不重要
boruta.ranking_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 5, 2, 1, 1, 1, 5, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
res = pd.DataFrame({'feature':data.columns.to_list(),'selected':boruta.support_})
res

feature  selected
0                                    AMT_GOODS_PRICE      True
1                         REGION_POPULATION_RELATIVE      True
2                                         DAYS_BIRTH      True
3                                      DAYS_EMPLOYED      True
4                                  DAYS_REGISTRATION      True
..                                               ...       ...
72                 p_PRODUCT_COMBINATION_Card Street      True
73           p_PRODUCT_COMBINATION_Cash Street: high      True
74           p_PRODUCT_COMBINATION_Cash X-Sell: high      True
75            p_PRODUCT_COMBINATION_Cash X-Sell: low      True
76  p_PRODUCT_COMBINATION_POS industry with interest      True

[77 rows x 2 columns]

In [14]:
res[res['selected'] == False]


feature  selected
27              b_CREDIT_DAY_OVERDUE     False
33          b_AMT_CREDIT_SUM_OVERDUE     False
37           b_CREDIT_TYPE_Microloan     False
38            b_CREDIT_TYPE_Mortgage     False
42         pos_cash_paid_late_12_cnt     False
55  p_NAME_CASH_LOAN_PURPOSE_Repairs     False
60        p_CODE_REJECT_REASON_SCOFR     False